image: node:11

pipelines:
  default:
    - step:
        name: Publish
        deployment: production
        script:
          - npm version minor -m "Upgrade to %s [skip ci]"
          - git push && git push --tags
          - pipe: atlassian/npm-publish:0.2.5
            variables:
              NPM_TOKEN: $NPM_TOKEN
