image: node:11

pipelines:
  default:
    - step:
        name: Publish
        deployment: production
        script:
          - >
            UPGRADE_TYPE='minor'
            COMMIT_MESSAGE=$(git log -1 --pretty='%B' | head -1)

            if [[ "${COMMIT_MESSAGE}" == *"(patch)"* ]]; then
              UPGRADE_TYPE='patch'
            elif [[ "${COMMIT_MESSAGE}" == *"(major)"* ]]; then
              UPGRADE_TYPE='patch'
            fi

            npm version ${UPGRADE_TYPE} -m "Upgrade to %s [skip ci]"

          - git push && git push --tags
          - pipe: atlassian/npm-publish:0.2.5
            variables:
              NPM_TOKEN: $NPM_TOKEN
